spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: rlaskagh776@gmail.com
    password: bmkfhrqcrcdsbxbj
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true